### ISSUE TITLE
Race condition in tests?

### ISSUE THREAD

**Issue by alexanderfefelov** [alexanderfefelov/kkmserver-api#1]
```
2018-09-28 07:28:00,944 kkmserver-api [DEBUG] request: {"Command":"OpenShift","IdCommand":"06corZ-SNFWKn-CeBObS-8iUin","NumDevice":3,"CashierName":"Швейк Йозеф","CashierVATIN":"987654321098"}
2018-09-28 07:28:00,944 kkmserver-api [DEBUG] request: {"Command":"ZReport","IdCommand":"1QAHP5-0CYyxU-ELww3Y-NUhS","NumDevice":3,"CashierName":"Швейк Йозеф","CashierVATIN":"987654321098"}
2018-09-28 07:28:01,032 kkmserver-api [DEBUG] response: {"Command":"ZReport","Error":"Ошибка регистрации ( 61 : ККТ: Смена не открыта или смена превысила 24 часа – операция невозможна )","Status":2,"IdCommand":"1QAHP5-0CYyxU-ELww3Y-NUhS","NumDevice":3,"UnitName":"baz"}
2018-09-28 07:28:01,050 kkmserver-api [DEBUG] request: {"Command":"GetRezult","IdCommand":"1QAHP5-0CYyxU-ELww3Y-NUhS"}
2018-09-28 07:28:01,056 kkmserver-api [DEBUG] response: {"CheckNumber":848,"SessionNumber":3,"Command":"OpenShift","Error":"","Status":0,"IdCommand":"06corZ-SNFWKn-CeBObS-8iUin","NumDevice":3,"UnitName":"baz"}
2018-09-28 07:28:01,091 kkmserver-api [DEBUG] response: {"Rezult":{"Command":"ZReport","Error":"Ошибка регистрации ( 61 : ККТ: Смена не открыта или смена превысила 24 часа – операция невозможна )","Status":2,"IdCommand":"1QAHP5-0CYyxU-ELww3Y-NUhS","NumDevice":3,"UnitName":"baz"},"Command":"GetRezult","Error":"","Status":0,"IdCommand":""}
```

**Comment by alexanderfefelov** [comment]
```
java.util.ConcurrentModificationException: Two threads have apparently attempted to run a suite at the same time. This has resulted in both threads attempting to concurrently change the current Informer. Suite class name: integration.KkmServerApiIntegration
	at org.scalatest.AsyncSuperEngine.$anonfun$runImpl$5(AsyncEngine.scala:626)
	at org.scalatest.AsyncSuperEngine.$anonfun$runImpl$5$adapted(AsyncEngine.scala:623)
	at org.scalatest.CompositeStatus.$anonfun$new$3(Status.scala:827)
	at org.scalatest.CompositeStatus.$anonfun$new$3$adapted(Status.scala:826)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at org.scalatest.CompositeStatus.$anonfun$new$2(Status.scala:826)
	at org.scalatest.CompositeStatus.$anonfun$new$2$adapted(Status.scala:799)
	at org.scalatest.CompositeStatus.$anonfun$new$3(Status.scala:827)
	at org.scalatest.CompositeStatus.$anonfun$new$3$adapted(Status.scala:826)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at org.scalatest.CompositeStatus.$anonfun$new$2(Status.scala:826)
	at org.scalatest.CompositeStatus.$anonfun$new$2$adapted(Status.scala:799)
	at org.scalatest.ScalaTestStatefulStatus.$anonfun$setCompleted$1(Status.scala:590)
	at org.scalatest.ScalaTestStatefulStatus.$anonfun$setCompleted$1$adapted(Status.scala:589)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at org.scalatest.ScalaTestStatefulStatus.setCompleted(Status.scala:589)
	at org.scalatest.Status.$anonfun$thenRun$2(Status.scala:235)
	at org.scalatest.Status.$anonfun$thenRun$2$adapted(Status.scala:226)
	at org.scalatest.ScalaTestStatefulStatus.$anonfun$setCompleted$1(Status.scala:590)
	at org.scalatest.ScalaTestStatefulStatus.$anonfun$setCompleted$1$adapted(Status.scala:589)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at org.scalatest.ScalaTestStatefulStatus.setCompleted(Status.scala:589)
	at org.scalatest.InternalFutureOutcome.$anonfun$new$1(AsyncOutcome.scala:44)
	at org.scalatest.InternalFutureOutcome.$anonfun$new$1$adapted(AsyncOutcome.scala:40)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at com.auvik.util.SequentialExecutionContext.$anonfun$execute$2(SequentialExecutionContext.scala:46)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
...
```
